from englisttohindi.englisttohindi import EngtoHindi
from translate import Translator
trans = EngtoHindi(message="Hello  Everyone  ")
trans = EngtoHindi(message="Candidate Login")
trans = EngtoHindi(message="Administrator Login")
trans = EngtoHindi(message="Candidate Info")
trans = EngtoHindi(message="Vote")
trans = EngtoHindi(message="View Results")
trans = EngtoHindi(message="View Profile")
trans = EngtoHindi(message="Change Profile")
trans = EngtoHindi(message="Jaydeep Singh")
trans = EngtoHindi(message="Candidate Info")
trans = EngtoHindi(message="Voting Results")
trans = EngtoHindi(message="News")
trans = EngtoHindi(message="Current Affair")
trans = EngtoHindi(message="Notice")
print(trans.convert)
translator= Translator(from_lang="english",to_lang="Gujarati")
translation = translator.translate("Logout")
print(translation)
